export default {
  // Counter
  CHANGE_LIST_TYPE: '@@list/CHANGE_LIST_TYPE',
  ADD_ITEM: '@@list/ADD_ITEM',
  CHANGE_STATUS: '@@list/CHANGE_STATUS',
  SET_LIST: '@@list/SET_LIST',
  CHANGE_TITLE: '@@list/CHANGE_TITLE',
  CHANGE_DESCRIPTION: '@@list/CHANGE_DESCRIPTION',
  CHANGE_PRIORITY: '@@list/CHANGE_PRIORITY',
  CHANGE_START_DATE: '@@list/CHANGE_START_DATE',
  CHANGE_END_DATE: '@@list/CHANGE_END_DATE',
  FILTER_LIST: '@@list/FILTER_LIST',
  DROP_FILTER: '@@list/DROP_FILTER',
}
